### ISSUE TITLE
Documentation Feature - Update the README for the Dockerfile

### ISSUE THREAD

**Issue by Hemanka** [DavidF09/fuzz4all#11]
- This addresses the user story #5 
- #12 #8 #10 are required to be completed.
- We will fill in extra details that are missing from the documentation that are helpful and important.
- It will be marked as accepted and complete if we can successfully set up the project by following the instructions in the README file.
- This should take approximately one day to complete.

**Comment by Farbubby** [comment]
## Update 1
- Originally I was going to add documentation on Sprint 1, but I realized I would need to document new changes my team makes to the repository so this task will be done for last.
