### ISSUE TITLE
Output Feature - Read the output from the file.

### ISSUE THREAD

**Issue by Hemanka** [DavidF09/fuzz4all#9]
- This addresses the user story #4 
- This feature will depend on the implementation of #8 
- This is estimated to take a few days or all of sprint 1.
- It will be marked as accepted and complete if it can read the output file correctly.

**Comment by DavidF09** [comment]
**Update**
- David will work on writing the coverage summaries to HTML files.
- Hemant will work on reading the csv files located in the bugs folder.

**Comment by DavidF09** [comment]
**Update**
- Hemant worked on reading the csv files located in the bugs folder.

**Comment by Hemanka** [comment]
For sprint 1, I worked on reading the .csv file located in the bugs folders. In sprint 2, I plan on formatting and displaying the read data on a webpage. During the sprint 2, I also plan on linking all the pages that I will be working to those that David has worked on.
